name: cv_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  audioplayers: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/

  fonts:
    - family: vazir
      fonts:
        - asset: fonts/vazir_fd_medium_wol.ttf
